# Generated by Django 3.2.6 on 2021-08-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0002_punjabi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gujarati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sabji_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Italian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='South_Indian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
    ]
