# Generated by Django 3.2.6 on 2021-08-04 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0003_gujarati_italian_south_indian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dish1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restro.punjabi')),
                ('Dish2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restro.gujarati')),
                ('Dish3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restro.south_indian')),
                ('Dish4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restro.italian')),
            ],
        ),
    ]
