# Generated by Django 3.2.6 on 2021-08-04 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0006_customer_dish1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.CharField(max_length=10)),
                ('Fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restro.punjabi')),
            ],
        ),
    ]
