# Generated by Django 3.2.6 on 2021-08-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0007_billing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='Fare',
            new_name='Fare1',
        ),
    ]
