# Generated by Django 3.2.6 on 2021-08-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0008_rename_fare_billing_fare1'),
    ]

    operations = [
        migrations.AddField(
            model_name='punjabi',
            name='Price',
            field=models.CharField(default=100, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
