# Generated by Django 3.2.6 on 2021-08-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0009_auto_20210804_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='gujarati',
            name='Price',
            field=models.CharField(default=100, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='italian',
            name='Price',
            field=models.CharField(default=200, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='south_indian',
            name='Price',
            field=models.CharField(default=150, max_length=10),
            preserve_default=False,
        ),
    ]
