# Generated by Django 3.2.6 on 2021-08-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0010_auto_20210804_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Dish2',
            field=models.ManyToManyField(to='restro.Gujarati'),
        ),
        migrations.AddField(
            model_name='customer',
            name='Dish3',
            field=models.ManyToManyField(to='restro.South_Indian'),
        ),
        migrations.AddField(
            model_name='customer',
            name='Dish4',
            field=models.ManyToManyField(to='restro.Italian'),
        ),
    ]
