# Generated by Django 3.2.6 on 2021-08-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0011_auto_20210804_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Dish2',
            field=models.ManyToManyField(blank=True, to='restro.Gujarati'),
        ),
    ]
