# Generated by Django 3.2.6 on 2021-08-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0012_alter_customer_dish2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Dish3',
            field=models.ManyToManyField(blank=True, to='restro.South_Indian'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Dish4',
            field=models.ManyToManyField(blank=True, to='restro.Italian'),
        ),
    ]
