# Generated by Django 3.2.6 on 2021-08-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0013_auto_20210804_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Dish1',
            field=models.ManyToManyField(blank=True, to='restro.Punjabi'),
        ),
    ]
